### ISSUE TITLE
Expanding the material database

### ISSUE THREAD

**Issue by jan-david-fischbach** [flaport/meow#10]
Hey @flaport,
where did you download the material data, that is part of meow so far?
As far as I can see the download from [refractiveindex.info](https://refractiveindex.info/?shelf=main&book=Si3N4&page=Kischkat#google_vignette) does not include the imaginary part of the refractive index.

**Comment by flaport** [comment]
I think I just copied the material data from a certain commercial tool which shall remain nameless 😅

**Comment by flaport** [comment]
But using the data from refractiveindex.info (is there an API?) would be a good start to expand the database :)

**Comment by simbilod** [comment]
See https://gist.github.com/lucas-flexcompute/5186955dc04dc2d1918cd7c6b5d59d5e for Python access to refractiveindexinfo

**Comment by jan-david-fischbach** [comment]
Similar functionality, that is pip installable: https://github.com/jtambasco/opticalmaterialspy

**Comment by jan-david-fischbach** [comment]
We might also use the tidy3D material database, which is based on refractiveindex.info as far as I can see

**Comment by flaport** [comment]
hmm since we're already using tidy3d as a dependency that might be a good idea. The opticalmaterialspy seems unmaintained...

**Comment by jan-david-fischbach** [comment]
Closing as completed
