### ISSUE TITLE
add spurious checker

### ISSUE THREAD

**Issue by jan-david-fischbach** [flaport/meow#13]
We could use a similar approach like emepy: 
https://github.com/BYUCamachoLab/emepy/blob/b22bd7e07a58b50d65be75569e5269640cf3bd4e/emepy/mode.py#L622

or we could determine the portion of power in (or close to) the PMLs

**Comment by flaport** [comment]
That looks like a good approach. Feel free to implement something like that when you find the time 😉

Or I might do it once I find some time, which might be in the slightly distant future.

**Comment by jan-david-fischbach** [comment]
Closing for now
