### ISSUE TITLE
Support for unequal number of modes in adjacent cross sections

### ISSUE THREAD

**Issue by jan-david-fischbach** [flaport/meow#14]
Currently meow fails complaining about the A matrix being non-square here:
https://github.com/flaport/meow/blob/a50f5e9938ceb7a1245fd33371d286f7a33eaf7d/meow/eme/common.py#L44

This can be solved as shown here:
https://github.com/Jan-David-Black/meow/tree/lstsq

which is analogous to the approach by emepy (taking the pseudo-inverse):
https://github.com/BYUCamachoLab/emepy/blob/b22bd7e07a58b50d65be75569e5269640cf3bd4e/emepy/models.py#L575

In my current branch sax however refuses to work with the resulting s-matrices and I dont really know why...
It just spits out an empty dict.

**Comment by jan-david-fischbach** [comment]
The problem seems to occur, when only a single mode is used at the input. Most commonly that can be avoided.

**Comment by jan-david-fischbach** [comment]
@flaport I prepared a (relatively) minimal example to reproduce the error here: https://colab.research.google.com/drive/1LbiA0w7ZUxCJIEYK3LQp5Xio0bGCBOgI?usp=sharing

**Comment by flaport** [comment]
I pulled in your changes from your main branch and your lstsq branch and made some final changes to the eme solver. It should be fixed now (changes available in version 0.3.5)

**Comment by jan-david-fischbach** [comment]
I should also close the other PR then?
