### ISSUE TITLE
Taper loss increases with length

### ISSUE THREAD

**Issue by joamatab** [flaport/meow#24]
How can we fix the gdsfactory plugin to work with latest version of meow?

**Comment by joamatab** [comment]
fixed by https://github.com/gdsfactory/gdsfactory/pull/1786

How can we improve the taper example?


https://gdsfactory.github.io/gdsfactory/notebooks/eme/01_meow.html

**Comment by jan-david-fischbach** [comment]
Hey @joamatab,
thanks for reporting here. I didn't realize that the new Materials were a breaking change. Sorry for that.
The odd taper simulations seem to be related to a insufficient number of cells (as little as 2 cells for the shortest taper). The number of cells (and with it the accuracy) increases with taper length - > more loss for longer taper. Retrying with a larger (but probably still insufficient) number of cells I get the following results. 
![descarga (2)](https://github.com/flaport/meow/assets/92856893/d08a9355-3c03-40f7-af69-cccb21c59a4d)
To reduce the number of cells required for convergence we should consider implementing Continuously Varying Cross-sectional Subcell (CVCS) similar to our role model ;) I'll open a separate issue on that regard.

**Comment by joamatab** [comment]
Could you share the code for this?

**Comment by jan-david-fischbach** [comment]
https://colab.research.google.com/drive/1leFtCpAlBmyURn0jbNKdO4YKl0mWDVmM?usp=sharing

**Comment by flaport** [comment]
Hi @joamatab ,

I updated the MEOW notebook in GDSFactory further. We're now getting a graph like this:

![image](https://github.com/flaport/meow/assets/15832886/e8f40e5a-2b86-4041-a88a-45f830c639e0)

see PR [here](https://github.com/gdsfactory/gdsfactory/pull/1799#issuecomment-1603379643)

I think this fixes the issue for now?
