### ISSUE TITLE
Taper sweep length

### ISSUE THREAD

**Issue by joamatab** [flaport/meow#3]
How can we sweep the length of a taper?

```python
import gdsfactory as gf
import numpy as np
from gdsfactory.simulation.eme import MEOW

layerstack = gf.tech.get_layer_stack_generic()

filtered_layerstack = gf.tech.LayerStack(
    layers={
        k: layerstack.layers[k]
        for k in (
            "slab90",
            "core",
            "box",
            "clad",
        )
    }
)


lengths = np.array([1, 20, 60, 100])
T = np.zeros_like(lengths, dtype=float)

for length in lengths:
    c = gf.components.taper(width2=10, length=length)
    c.plot()

for i, length in enumerate(lengths):
    c = gf.components.taper(width2=10, length=length)
    eme = MEOW(component=c, layerstack=filtered_layerstack, wavelength=1.55)
    sp = eme.compute_sparameters()
    T[i] = np.abs(sp['o1@0,o2@0'])**2

import matplotlib.pyplot as plt

plt.plot(lengths, T, '.')
plt.title('Fundamental mode transmission')
plt.ylabel('Transmission')
plt.xlabel('taper length (um)')
```

I would expect a short taper would have more loss

![image](https://user-images.githubusercontent.com/4514346/208750580-102b4e8e-148e-416d-8cf5-9a5a18c16e5a.png)

**Comment by flaport** [comment]
Are you sure the EME cell length remains constant between simulations? If the eme cell length is not constant it's probably not a fair comparison... I've added a very basic example [here](https://github.com/flaport/meow/blob/main/examples/02_taper_length_sweep.ipynb) which does show that a shorter taper seems to have more loss.

**Comment by joamatab** [comment]
Thank you Floris for the example

**Comment by joamatab** [comment]
the taper for the gdsfactory still has some issues

https://gdsfactory.github.io/gdsfactory/notebooks/plugins/eme/01_meow.html

**Comment by simbilod** [comment]
See https://github.com/gdsfactory/gdsfactory/pull/1038, we need to make sure simulation hyperparameters are fine enough

**Comment by joamatab** [comment]
yes, thank you Simon and Floris, the cell_length was too small :)
