### ISSUE TITLE
Self defined material and profile monitor

### ISSUE THREAD

**Issue by SprBull** [flaport/meow#37]
Mr Laporte, 

I am new to this fantastic tool and I am obsessed with it already.  Thank you for developing such a rare jewel!

Please forgive me for asking two simple questions (I am new..):

1. How can one define a non built-in material with a refractive index? What are the relevant classes, variables as well as syntax for this?
2. In addition to S-matrix, a propagation profile is also desirable for understanding. How can one plot it and again what are the relevant classes, variables as well as syntax for this?

Thanks a lot in advance!

**Comment by jan-david-fischbach** [comment]
Hey @SprBull, the following code can be used to manually define a nondispersive material:

```python
mat = meow.IndexMaterial(name="custom", n=1.45)
```

The [mmi notebook](https://colab.research.google.com/github/flaport/meow/blob/main/tests/nbs/mmi.ipynb) found in the tests folder can maybe help you get started visualizing fields (which is not jet stable and well tested). Make sure to run 
```
pip install meow-sim gdsfactory==8.0.0
```
before running the notebook in colab. I fixed the version of gdsfactory here, as I get an error at import time for the newest version :/

I hope this is in any way helpful, should there be questions remaining please hit me up. Best JD
