### ISSUE TITLE
documentation suggestions

### ISSUE THREAD

**Issue by lukasc-ubc** [flaport/meow#40]
Hello Floris,

I could not find anywhere in the documentation where to set the wavelength for the simulations.  I am guessing it has a default somewhere of 1.55 µm?  In the example, I see "wl=1.55".

The example https://flaport.github.io/meow/examples/02_taper_length_sweep.html calls tqdm, which is undefined:
`    for cs in tqdm(css):
`

adding
`from tqdm import tqdm
`
helps.

It would be helpful to describe the S-matrix format, e.g., top left quadrant is the back-reflection, top right is the transmission.  Use abs(S1[num_modes][0]) to find the transmission amplitude for the fundamental mode.

**Comment by jan-david-fischbach** [comment]
Hey  @lukasc-ubc,

please excuse the slightly late reply. Thanks a lot for the helpful comments!

### 1. Wavelength
The vacuum wavelength is set in the meow.Environment that has to be provided when converting a cell to a cross section
From the [quick start guide](https://flaport.github.io/meow/examples/00_introduction.html):
>3. Cross Sections
A [Cell](https://flaport.github.io/meow/meow.html#meow.cell.Cell) contains all the Structure info, but does not take any [Environment](https://flaport.github.io/meow/meow.html#meow.environment.Environment) information (such as temparature or **wavelength**) into account. This information is important as it influences the refractive index of the [CrossSection](https://flaport.github.io/meow/meow.html#meow.cross_section.CrossSection).

which is then set as 
``` python
env = mw.Environment(wl=1.55, T=25.0)
```

I hope this is clear enough?

### 2. `tqdm`
In the generated html all imports at the beginning of the notebook are hidden. If you use the rocket icon to launch an interactive session (i.e. in colab: https://colab.research.google.com/github/flaport/meow/blob/main/examples/02_taper_length_sweep.ipynb) these imports (including `tqdm`) should be present. How did you run the notebook on your end?

### 3. Documentation of the S-matrix layout
I'll add the following description in the quick-start guide:
> The resulting S-matrix has is formated such that `S[0][0]` is the complex reflection coefficient from the fundamental mode into the backwards propagating fundamental mode. `S[num_modes][0]` is the transmission from the fundamental mode into the fundamental mode, following the pattern `S[<to_port>][<from_port>]`. The mapping from ports to indices is provided in `port_map`.

I hope this will help
Thanks again for the feedback
Regards JD
