### ISSUE TITLE
Kernel crashes when using PML

### ISSUE THREAD

**Issue by jan-david-fischbach** [flaport/meow#9]
The ipython kernel crashes without an error message when specifying any `num_pml` unequal to (0,0) and using `compute_modes` subsequently on an M1 mac.
I suspect there is an incompatibility between the Tidy3D FDE solver and m1 silicon. I have however not yet traced back the origin of the crash.

The issue looks similar to https://github.com/microsoft/vscode-jupyter/issues/9741
However, I do not run out of memory while the kernel crashes.

**Comment by flaport** [comment]
Interesting... I don't have an M1 mac, so I can't reproduce the problem. But I'll leave this open to keep track of.

**Comment by jan-david-fischbach** [comment]
I actually encounter the same problem on an ubuntu machine :/

**Comment by flaport** [comment]
Can you create a minimal example?

**Comment by jan-david-fischbach** [comment]
Of course, I just got caught up doing other stuff. I'll keep you posted.

**Comment by flaport** [comment]
@Jan-David-Black , are we still seeing this issue?

**Comment by jan-david-fischbach** [comment]
Haven't had it for a while. I have noticed that running low on ram tends to kill the kernel, but I think that is something that needs to be discussed somewhere else. I'll close the issue. If anyone runs into related problem feel free to reopen

**Comment by flaport** [comment]
Yeah, I have seen my kernel die in the past too when working with JAX or klujax when I'm running out of memory.
